import { createWalletClient, http, createPublicClient, defineChain } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import * as fs from "fs";
import { loadEnvFiles } from "./load-env";

loadEnvFiles();

const hederaChain = defineChain({
  id: 296,
  name: "Hedera Testnet",
  nativeCurrency: { name: "HBAR", symbol: "HBAR", decimals: 18 },
  rpcUrls: { default: { http: ["https://testnet.hashio.io/api"] } },
});

async function main() {
  const privateKey = process.env.HEDERA_OPERATOR_PRIVATE_KEY;
  if (!privateKey) throw new Error("Missing HEDERA_OPERATOR_PRIVATE_KEY");

  const account = privateKeyToAccount(privateKey as `0x${string}`);
  
  const walletClient = createWalletClient({
    account,
    chain: hederaChain,
    transport: http("https://testnet.hashio.io/api"),
  });

  const publicClient = createPublicClient({
    chain: hederaChain,
    transport: http("https://testnet.hashio.io/api"),
    pollingInterval: 2_000,
  });

  // Read ABI and Bytecode generated by solcjs
  const abiRaw = fs.readFileSync("../packages/shared/abi/VeriChainRegistry.json", "utf-8");
  const binRaw = fs.readFileSync("./scripts/VeriChainRegistry.bin", "utf-8");

  const abi = JSON.parse(abiRaw);
  const bytecode = `0x${binRaw.trim()}` as `0x${string}`;

  console.log("Deploying contract from:", account.address);

  const hash = await walletClient.deployContract({
    abi,
    bytecode,
    gas: 2_000_000n,
    type: "legacy",
  });

  console.log("Tx Hash:", hash);
  const receipt = await publicClient.waitForTransactionReceipt({ hash, timeout: 60000 });
  
  console.log("Deployed at:", receipt.contractAddress);
}

main().catch(console.error);
