create table if not exists shipments (
  id bigint primary key,
  product_id bigint not null,
  sender text not null,
  receiver text not null,
  status text not null,
  tx_hash text,
  created_at timestamptz not null default now()
);

create table if not exists custody_transfers (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  from_address text not null,
  to_address text not null,
  tx_hash text,
  created_at timestamptz not null default now()
);

create table if not exists checkpoints (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  latitude numeric not null,
  longitude numeric not null,
  checkpoint text not null,
  observed_at timestamptz not null,
  risk_score integer,
  tx_hash text,
  created_at timestamptz not null default now()
);

create table if not exists anomalies (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  risk_score integer not null check (risk_score between 0 and 100),
  reason text not null,
  status text not null default 'OPEN',
  tx_hash text,
  created_at timestamptz not null default now()
);

create table if not exists escrows (
  id bigint primary key,
  product_id bigint not null,
  payer text not null,
  payee text not null,
  amount_wei numeric not null,
  status text not null,
  tx_hash text,
  created_at timestamptz not null default now()
);