alter table checkpoints add column if not exists request_id text;
alter table anomalies add column if not exists request_id text;
alter table anomalies add column if not exists explanation text;
alter table anomalies add column if not exists resolved_at timestamptz;

create unique index if not exists checkpoints_request_id_idx
  on checkpoints(request_id) where request_id is not null;
create unique index if not exists anomalies_request_id_idx
  on anomalies(request_id) where request_id is not null;

create table if not exists payments (
  id bigint generated by default as identity primary key,
  request_id text not null unique,
  resource text not null,
  payer text not null,
  amount numeric not null check (amount >= 0),
  currency text not null,
  network text not null,
  transaction_id text not null unique,
  expires_at bigint not null,
  status text not null check (status in ('VERIFIED', 'REJECTED')),
  created_at timestamptz not null default now()
);

create index if not exists checkpoints_product_observed_idx
  on checkpoints(product_id, observed_at desc);
create index if not exists anomalies_product_status_idx
  on anomalies(product_id, status);