-- VeriChain Supply Chain Migration 003
-- Ensures all 5 core tables exist with indexes, constraints, and RLS policies

-- 1. Shipments table
create table if not exists shipments (
  id bigint primary key,
  product_id bigint not null,
  sender text not null,
  receiver text not null,
  status text not null check (status in ('CREATED', 'IN_TRANSIT', 'RECEIVED', 'CANCELLED')),
  tx_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. Custody transfers table
create table if not exists custody_transfers (
  id bigint generated by default as identity primary key,
  product_id bigint not null,
  from_address text not null,
  to_address text not null,
  tx_hash text,
  created_at timestamptz not null default now()
);

-- 3. Checkpoints table
create table if not exists checkpoints (
  id bigint generated by default as identity primary key,
  request_id text,
  product_id bigint not null,
  latitude numeric not null check (latitude between -90 and 90),
  longitude numeric not null check (longitude between -180 and 180),
  checkpoint text not null,
  observed_at timestamptz not null,
  risk_score integer check (risk_score between 0 and 100),
  tx_hash text,
  created_at timestamptz not null default now()
);

-- 4. Anomalies table
create table if not exists anomalies (
  id bigint generated by default as identity primary key,
  request_id text,
  product_id bigint not null,
  risk_score integer not null check (risk_score between 0 and 100),
  reason text not null,
  explanation text,
  status text not null default 'OPEN' check (status in ('OPEN', 'RESOLVED', 'DISMISSED')),
  tx_hash text,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

-- 5. Escrows table
create table if not exists escrows (
  id bigint primary key,
  product_id bigint not null,
  payer text not null,
  payee text not null,
  amount_wei numeric not null check (amount_wei >= 0),
  status text not null check (status in ('ACTIVE', 'FROZEN', 'RELEASED', 'RESOLVED')),
  tx_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Indexes for fast querying
create index if not exists shipments_product_id_idx on shipments(product_id);
create index if not exists shipments_sender_idx on shipments(sender);
create index if not exists shipments_receiver_idx on shipments(receiver);
create index if not exists custody_transfers_product_id_idx on custody_transfers(product_id);
create index if not exists checkpoints_product_id_idx on checkpoints(product_id, observed_at desc);
create index if not exists anomalies_product_id_idx on anomalies(product_id, status);
create index if not exists escrows_product_id_idx on escrows(product_id);

-- Enable RLS and grant read/write to anon and service_role for hackathon
alter table shipments enable row level security;
alter table custody_transfers enable row level security;
alter table checkpoints enable row level security;
alter table anomalies enable row level security;
alter table escrows enable row level security;

-- Drop existing policies if any to avoid duplication
drop policy if exists "Public shipments access" on shipments;
drop policy if exists "Public custody access" on custody_transfers;
drop policy if exists "Public checkpoints access" on checkpoints;
drop policy if exists "Public anomalies access" on anomalies;
drop policy if exists "Public escrows access" on escrows;

create policy "Public shipments access" on shipments for all using (true) with check (true);
create policy "Public custody access" on custody_transfers for all using (true) with check (true);
create policy "Public checkpoints access" on checkpoints for all using (true) with check (true);
create policy "Public anomalies access" on anomalies for all using (true) with check (true);
create policy "Public escrows access" on escrows for all using (true) with check (true);

-- Reload PostgREST schema cache
notify pgrst, 'reload schema';
